version: "3.7"

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - '127.0.0.1:81:81'
      - 443:443
    volumes:
      - ./containers/nginx/data:/data
      - ./containers/nginx/letsencrypt:/etc/letsencrypt

  plex:
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    restart: unless-stopped
    ports:
      - ${PLEX_PORT}:32400
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - PLEX_PASS=${PLEX_PASS}
    volumes:
      - ./containers/plex/config:/config
      - ./containers/plex/transcode:/transcode
      - ./downloads:/downloads
    networks:
      - seedbox

  tautulli:
    container_name: tautulli
    image: cr.hotio.dev/hotio/tautulli
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ./containers/tautulli/config:/config
    networks:
      - seedbox

  rflood:
    container_name: rflood
    image: cr.hotio.dev/hotio/rflood
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - FLOOD_AUTH=${FLOOD_AUTH}
    volumes:
      - ./containers/rflood/config:/config
      - ./downloads:/downloads
    networks:
      - seedbox

  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ./containers/jackett/config:/config
    networks:
      - seedbox

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ./containers/sonarr/config:/config
      - ./downloads:/downloads
    networks:
      - seedbox

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ./containers/radarr/config:/config
      - ./downloads:/downloads
    networks:
      - seedbox

  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr
    restart: unless-stopped
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ./containers/overseerr/config:/config
      - ./downloads:/downloads
    networks:
      - seedbox

networks:
  seedbox:
    name: seedbox
    driver: bridge